### PR TITLE
Adapt `./everest check` and `windows-init.ps1` to run on official opam 2.3 for Windows+Cygwin

### PR DESCRIPTION
**Pull request by tahina-pro**
Since August 2024, [opam has been officially supporting Windows](https://ocaml.org/docs/ocaml-on-windows), replacing previous installers such as [fdopen](https://fdopen.github.io/opam-repository-mingw/), which was used by CI for Everest components so far.

This PR fixes `./everest check` (which is used to check for dependencies of Everest and install them on Windows) and `windows-init.ps1` (which is used to set up a Windows CI machine from scratch) to run on Windows+Cygwin with official opam 2.3.

With this PR, using FStarLang/FStar#3630, FStarLang/karamel#503 and hacl-star/hacl-star#1011, `./everest make` and `./everest test` successfully work on Windows+Cygwin with official opam 2.3 (and OCaml 5.2.1): https://github.com/project-everest/everest/actions/runs/12239757622

Once those individual PRs are merged and taken into `master` by Everest upgrade, I will update `hashes.sh` accordingly and make this PR ready.

This PR brings in the following changes:

# `./everest check`

* On Windows, `./everest check` now installs OCaml 5.2.1 if not found
* now, `./everest check` no longer lets opam auto-setup its environment in the user's init script. opam auto-setup makes ocamlfind fail to compile on Windows because of dra27/mingw-w64-shims#2. Instead, `setup_env` now runs `eval $(opam env)`. Thus, Linux CI no longer needs to auto-setup opam's environment or run Everest with `eval $(opam env)` either. (But `eval $(opam env)` will be necessary for individual components of Everest without the `everest` script)
* `./everest check` now ignores errors by `opam depext` (with the official opam 2.3, depext-cygwinports no longer exists, and `opam depext` is done by default by `opam install`)
* On Windows, `./everest check` now checks for ocamlfind >= 1.9.8, because the compilation of HACL* OCaml bindings hit ocaml/opam#6129, whose fix, ocaml/ocamlfind#64, was not merged until that release. (See also ocaml/opam-repository#26510) If no such ocamlfind is found, then `./everest check` now installs ocamlfind 1.9.8 by manually checking it out from GitHub, since that version has not been uploaded to the opam package repository yet
* `./everest check` now checks for Rust (required by Karamel tests) on all platforms, and offers to install Rust via [RustUp](https://rustup.rs/) on Windows. In that case, RustUp proposes to install Visual Studio or anything like that, the Everest script does not need to care.
* `./everest check` now uses WinGet to install Node.js (required by Karamel tests) and .NET 6 (required to extract F*'s standard library to F#) on Windows
* On Windows, `setup_env` now defines `CC` to use the mingw64 compiler instead of Cygwin's gcc. This is necessary for Karamel ctypes tests (at least) to compile. However, contrary to `CXX`, `./everest check` cannot auto-setup `CC` into the user's init script, because this breaks the compilation of opam packages such as `alcotest`, `sha`, etc.: if `CC` is defined, `dune` will complain about the mingw64 compiler not found. (I have not found any relevant GitHub issue yet.)

# Other changes

* Installing the official opam for windows now requires a refresh of the PATH. I don't know how to do that in `bash`, but I know how to do that in PowerShell. So, I let `./everest check` abort, and I have `windows-init.ps1` run `./everest check` as many times as necessary, refreshing the PATH in between two runs, until two consecutive successful runs.
* `cryptokit` is no longer used, so it is removed from required opam packages. It is not available with OCaml >= 5.0.
* A new GitHub Actions workflow for Windows+Cygwin with official opam 2.3

### CODE REVIEW

**Review by msprotz — COMMENTED** [review]
Is winget something universally available?

**Comment by msprotz** [comment]
Looks good to me except for maybe clarification about where winget comes frome

**Comment by tahina-pro** [comment]
Microsoft recently introduced an [official Microsoft Windows package manager](https://learn.microsoft.com/en-us/windows/package-manager/), with [WinGet as one of the official command-line interfaces](https://learn.microsoft.com/en-us/windows/package-manager/winget/).
WinGet is now part of Windows 11 and recent versions of Windows 10. Otherwise, it can also be installed via https://aka.ms/getwinget , which I am doing in `windows-init.ps1` to set up an Everest CI machine: https://github.com/project-everest/everest/blob/98d0353b6ddd6bb8e021ea0a6760a801710995d8/windows-init.ps1#L40C24-L40C48
WinGet is open-source, available on GitHub: https://github.com/microsoft/winget-cli

**Comment by tahina-pro** [comment]
Yet another Windows green: https://github.com/project-everest/everest/actions/runs/12281960373

**Comment by tahina-pro** [comment]
Thank you everyone for having merged the corresponding PRs in each component!

**Pull request merged**
