### PR TITLE
Do not assume make == gmake

### PR DESCRIPTION
**Pull request by web-vertalo**
Replace `make` with `$MAKE`

### CODE REVIEW

**Review by msprotz — CHANGES_REQUESTED** [review]
Thanks. This looks good, except $MAKE is not always defined, so could you add something that defaults to `make`?

**Comment by web-vertalo** [comment]
Does the existing MAKE definition not suffice:
```
MAKE=$(which gmake >/dev/null 2>&1 && echo gmake || echo make)
```

**Review by msprotz — APPROVED** [review]
Indeed it does. I just assumed that if there were bare references in the file to `make`, surely, it must be because no one defined a proper `MAKE` variable. But I did define `MAKE` in that file a while back. Looks good to me, thanks.

**Comment by msprotz** [comment]
I'm adding Tahina as a reviewer before merging since this may impact his work

**Review by tahina-pro — APPROVED** [review]

**Comment by msprotz** [comment]
Thanks @tahina-pro

**Pull request merged**
